all:
	@g++ -I /home/manager/Desktop/BioInf/LinuxUnitTest/ ../WaveletTree/WaveletTree/RRR.cpp ../WaveletTree/WaveletTree/RRRTable.cpp ../WaveletTree/WaveletTree/WaveletNode.cpp ../WaveletTree/WaveletTree/WaveletTree.cpp -o main tests.cpp -std=c++11
